basePath: /
definitions:
  book.Chapter:
    properties:
      index:
        description: 章节序号
        type: integer
      name:
        description: 章节名称
        type: string
      url:
        description: 链接
        type: string
    type: object
  book.GetBookDirectoryResp:
    properties:
      data_list:
        items:
          $ref: '#/definitions/model.Chapter'
        type: array
      total:
        type: integer
    type: object
  deleteat.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Book:
    properties:
      author:
        description: 作者
        type: string
      book_type:
        description: 类型
        type: string
      brief:
        description: 简介
        type: string
      chapter_list:
        description: 定义 Has Many 关系
        items:
          $ref: '#/definitions/model.Chapter'
        type: array
      create_at:
        type: string
      delete_at:
        $ref: '#/definitions/deleteat.DeletedAt'
      id:
        type: integer
      img_url:
        description: 图片链接
        type: string
      last_chapter:
        $ref: '#/definitions/book.Chapter'
        description: 最近更新章节
      last_update_time:
        description: 最近更新时间
        type: string
      name:
        description: 书名
        type: string
      source:
        description: 来源
        type: string
      update_at:
        type: string
      url:
        description: 链接
        type: string
    type: object
  model.Chapter:
    properties:
      book_id:
        type: integer
      content:
        type: string
      create_at:
        type: string
      delete_at:
        $ref: '#/definitions/deleteat.DeletedAt'
      id:
        type: integer
      index:
        description: 章节序号
        type: integer
      name:
        description: 章节名称
        type: string
      update_at:
        type: string
      url:
        description: 链接
        type: string
    type: object
  ping.PingResp:
    properties:
      hello:
        type: string
    type: object
  search.SearchReq:
    properties:
      keyword:
        description: 搜索关键字
        maxLength: 20
        minLength: 1
        type: string
      limit:
        default: 10
        description: 限制结果数量
        maximum: 100
        minimum: 1
        type: integer
    required:
    - keyword
    type: object
  search.SearchResp:
    properties:
      data_list:
        items:
          $ref: '#/definitions/model.Book'
        type: array
      total:
        type: integer
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: zhenhua32@xingkong.io
    name: API Support
    url: http://xingkong.io/support
  description: 行空 API, 用于小说搜索
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 行空 API
  version: "1.0"
paths:
  /book/{id}:
    get:
      consumes:
      - text/html
      description: 返回小说的详情
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: 返回小说的详情
      tags:
      - book
  /book/{id}/directory:
    get:
      consumes:
      - text/html
      description: 返回小说的目录
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.GetBookDirectoryResp'
      summary: 返回小说的目录
      tags:
      - book
  /chapter/{id}:
    get:
      consumes:
      - text/html
      description: 返回章节的详情
      parameters:
      - description: 章节ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Chapter'
      summary: 返回章节的详情
      tags:
      - chapter
  /ping:
    get:
      consumes:
      - text/html
      description: 测试连接是否正常
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.PingResp'
      summary: 测试连接是否正常
      tags:
      - 监控
  /search:
    post:
      consumes:
      - application/json
      description: 返回小说的搜索结果
      operationId: search
      parameters:
      - description: 搜索参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/search.SearchReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/search.SearchResp'
      summary: 返回小说的搜索结果
      tags:
      - 搜索
swagger: "2.0"
